{% set name = "mdformat-pyproject" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mdformat_pyproject-{{ version }}.tar.gz
  sha256: 1638c4be0d239f49eea72089aafd06dc4ec603068ccc4868f91f0958b15b82c8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - mdformat >=0.7,<1
    # for all python to stay noarch: python
    - tomli >=2.0,<3

test:
  imports:
    - mdformat_pyproject
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: An mdformat plugin to read configuration from pyproject.toml
  home: https://pypi.org/project/mdformat-pyproject/
  dev_url: https://github.com/csala/mdformat-pyproject
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anjos
